void p00_dat ( int prob, int data_num, double x[], double y[] );
int p00_data_num ( int prob );
int p00_prob_num ( void );
void p00_story ( int prob );
void p00_title ( int prob, char *title );
void p01_dat ( int data_num, double x[], double y[] );
int p01_data_num ( void );
void p01_story ( void );
void p01_title ( char *title );
void p02_dat ( int data_num, double x[], double y[] );
int p02_data_num ( void );
void p02_story ( void );
void p02_title ( char *title );
void p03_dat ( int data_num, double x[], double y[] );
int p03_data_num ( void );
void p03_story ( void );
void p03_title ( char *title );
void p04_dat ( int data_num, double x[], double y[] );
int p04_data_num ( void );
void p04_story ( void );
void p04_title ( char *title );
void p05_dat ( int data_num, double x[], double y[] );
int p05_data_num ( void );
void p05_story ( void );
void p05_title ( char *title );
void p06_dat ( int data_num, double x[], double y[] );
int p06_data_num ( void );
void p06_story ( void );
void p06_title ( char *title );
void p07_dat ( int data_num, double x[], double y[] );
int p07_data_num ( void );
void p07_story ( void );
void p07_title ( char *title );
void p08_dat ( int data_num, double x[], double y[] );
int p08_data_num ( void );
void p08_story ( void );
void p08_title ( char *title );
void p09_dat ( int data_num, double x[], double y[] );
int p09_data_num ( void );
void p09_story ( void );
void p09_title ( char *title );
void p10_dat ( int data_num, double x[], double y[] );
int p10_data_num ( void );
void p10_story ( void );
void p10_title ( char *title );
void r8vec_copy ( int n, double a1[], double a2[] );
void r8vec2_print ( int n, double a1[], double a2[], char *title );
void r8vec2_write ( char *output_filename, int n, double x[], double y[] );
