double *p00_f ( int prob, int n, double x[] );
int p00_prob_num ( void );
char *p00_title ( int prob );
double *p01_f ( int n, double x[] );
char *p01_title ( void );
double *p02_f ( int n, double x[] );
char *p02_title ( void );
double *p03_f ( int n, double x[] );
char *p03_title ( void );
double *p04_f ( int n, double x[] );
char *p04_title ( void );
double *p05_f ( int n, double x[] );
char *p05_title ( void );
double *p06_f ( int n, double x[] );
char *p06_title ( void );
double *p07_f ( int n, double x[] );
char *p07_title ( void );
double *p08_f ( int n, double x[] );
char *p08_title ( void );
