int a_to_i4 ( char ch );
int base_to_i4 ( char *s, int base );
void byte_to_int ( unsigned char *bvec, unsigned int *ival );
char ch_cap ( char ch );
void ch_count_cvec_add ( int n, unsigned char cvec[], int count[256] );
int ch_eqi ( char ch1, char ch2 );
int ch_index_first ( char *s, char c );
int ch_index_last ( char *s, char c );
int ch_is_alpha ( char ch );
int ch_is_alphanumeric ( char ch );
int ch_is_control ( char ch );
int ch_is_digit ( char ch );
int ch_is_lower ( char c );
int ch_is_space ( char c );
char ch_low ( char ch );
char ch_read ( FILE *filein );
int ch_roman_to_i4 ( char ch );
char ch_scrabble ( int tile );
void ch_swap ( char *ch1, char *ch2 );
int ch_to_digit ( char ch );
int ch_to_digit_bin ( char c );
char ch_to_rot13 ( char ch );
char ch_uniform ( char clo, char chi, int *seed );
char digit_inc ( char c );
char digit_to_ch ( int digit );
int hex_digit_to_i4 ( char c );
int i4_huge ( void );
int i4_log_10 ( int i );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
void i4_swap ( int *i, int *j );
char i4_to_a ( int i );
char i4_to_amino_code ( int i );
char i4_to_hex_digit ( int i );
char i4_to_isbn ( int i );
char *i4_to_s ( int i );
int i4_uniform ( int a, int b, int *seed );
int isbn_to_i4 ( char c );
int r4_nint ( float x );
double r8_uniform_01 ( int *seed );
void s_adjustl ( char *s );
int s_begin ( char *s1, char *s2 );
void s_blank_delete ( char *s );
void s_blanks_delete ( char *s );
void s_cap ( char *s );
char *s_cat ( char *s1, char *s2 );
int s_ch_count ( char *s, char ch );
char *s_ch_delete ( char *s, char ch );
void s_control_blank ( char *s );
int s_eqi ( char *s1, char *s2 );
char *s_escape_tex ( char *s1 );
char *s_first_ch ( char *s, char ch );
char *s_first_nonblank ( char *s );
int s_index_last_c ( char *s, char c );
int s_len_trim ( char *s );
void s_low ( char *s );
void s_newline_to_null ( char *s );
void s_replace_ch ( char *s, char c1, char c2 );
char *s_reverse ( char *s );
void s_sort_a ( char *s );
int s_to_i4 ( char *s, int *last, int *error );
int s_to_i4vec ( char *s, int n, int ivec[] );
int s_to_l ( char *s );
float s_to_r4 ( char *s, int *lchar, int *error );
int s_to_r4vec ( char *s, int n, float rvec[] );
double s_to_r8 ( char *s, int *lchar, int *error );
int s_to_r8vec ( char *s, int n, double rvec[] );
void s_to_rot13 ( char *s );
void s_word_cap ( char *s );
int s_word_count ( char *s );
char *s_word_extract_first ( char *s );
void sort_heap_external ( int n, int *indx, int *i, int *j, int isgn );
void timestamp ( void );

