char ch_cap ( char ch );
int ch_eqi ( char ch1, char ch2 );
int ch_to_digit ( char ch );
int file_column_count ( char *input_filename );
int file_row_count ( char *input_filename );
int i4_log_10 ( int i );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
int i4_power ( int i, int j );
int *i4mat_indicator_new ( int m, int n );
void i4mat_print ( int m, int n, int a[], char *title );
void i4mat_print_some ( int m, int n, int a[], int ilo, int jlo, int ihi, 
  int jhi, char *title );
int *i4mat_border_add ( int m, int n, int table[] );
int *i4mat_border_cut ( int m, int n, int table[] );
int *i4mat_data_read ( char *input_filename, int m, int n );
void i4mat_header_read ( char *input_filename, int *m, int *n );
int *i4mat_read ( char *input_filename, int *m, int *n );
void i4mat_write ( char *output_filename, int m, int n, int table[] );
int *lvec_data_read ( char *input_filename, int n );
void lvec_header_read ( char *input_filename, int *n );
void lvec_write ( char *output_filename, int n, int table[] );
float *r4mat_data_read ( char *input_filename, int m, int n );
void r4mat_header_read ( char *input_filename, int *m, int *n );
float *r4mat_indicator_new ( int m, int n );
float *r4mat_uniform_01 ( int m, int n, int *seed );
void r4mat_print ( int m, int n, float a[], char *title );
void r4mat_print_some ( int m, int n, float a[], int ilo, int jlo, int ihi, 
  int jhi, char *title );
float *r4mat_read ( char *input_filename, int *m, int *n );
void r4mat_transpose_print ( int m, int n, float a[], char *title );
void r4mat_transpose_print_some ( int m, int n, float a[], int ilo, int jlo, 
  int ihi, int jhi, char *title );
void r4mat_write ( char *output_filename, int m, int n, float table[] );
double *r8mat_border_add ( int m, int n, double table[] );
double *r8mat_border_cut ( int m, int n, double table[] );
double *r8mat_data_read ( char *input_filename, int m, int n );
void r8mat_header_read ( char *input_filename, int *m, int *n );
double *r8mat_indicator_new ( int m, int n );
double *r8mat_uniform_01 ( int m, int n, int *seed );
void r8mat_print ( int m, int n, double a[], char *title );
void r8mat_print_some ( int m, int n, double a[], int ilo, int jlo, int ihi, 
  int jhi, char *title );
double *r8mat_read ( char *input_filename, int *m, int *n );
void r8mat_transpose_print ( int m, int n, double a[], char *title );
void r8mat_transpose_print_some ( int m, int n, double a[], int ilo, int jlo, 
  int ihi, int jhi, char *title );
void r8mat_write ( char *output_filename, int m, int n, double table[] );
double *r8vec_data_read ( char *input_filename, int n );
void r8vec_header_read ( char *input_filename, int *n );
void r8vec_write ( char *output_filename, int n, double x[] );
void r8vec2_write ( char *output_filename, int n, double x[], double y[] );
void r8vla2_write ( char *output_filename, int m, int n, double a[m][n] );
int s_len_trim ( char *s );
int s_to_i4 ( char *s, int *last, int *error );
int s_to_i4vec ( char *s, int n, int ivec[] );
int s_to_l ( char *s );
float s_to_r4 ( char *s, int *lchar, int *error );
int s_to_r4vec ( char *s, int n, float rvec[] );
double s_to_r8 ( char *s, int *lchar, int *error );
int s_to_r8vec ( char *s, int n, double rvec[] );
int s_word_count ( char *s );
void timestamp ( void );
