float         c4_abs ( float complex c );
float complex c4_acos ( float complex c1 );
float complex c4_acosh ( float complex c1 );
float complex  c4_add ( float complex c1, float complex c2 );
float          c4_arg ( float complex c );
float complex  c4_asin ( float complex c1 );
float complex  c4_asinh ( float complex c1 );
float complex  c4_atan ( float complex c1 );
float complex  c4_atanh ( float complex c1 );
float complex  c4_conj ( float complex c1 );
void           c4_copy ( float complex c1, float complex c2 );
float complex  c4_cos ( float complex c1 );
float complex  c4_cosh ( float complex c1 );
float complex  c4_cube_root ( float complex c1 );
float complex  c4_div ( float complex c1, float complex c2 );
float complex  c4_div_r4 ( float complex c1, float r );
float complex  c4_exp ( float complex c1 );
float complex  c4_i ( void );
float          c4_imag ( float complex c );
float complex  c4_inv ( float complex c1 );
float complex  c4_log ( float complex c1 );
float          c4_mag ( float complex c );
float complex  c4_mul ( float complex c1, float complex c2 );
float complex  c4_neg ( float complex c1 );
float complex  c4_normal_01 ( int *seed );
float complex  c4_one ( void );
float          c4_real ( float complex c );
float complex  c4_sin ( float complex c1 );
float complex  c4_sinh ( float complex c1 );
float complex  c4_sqrt ( float complex c1 );
float complex  c4_sub ( float complex c1, float complex c2 );
void           c4_swap ( float complex c1, float complex c2 );
float complex  c4_tan ( float complex c1 );
float complex  c4_tanh ( float complex c1 );
void           c4_to_cartesian ( float complex c, float *x, float *y );
void           c4_to_polar ( float complex c, float *r, float *theta );
float complex  c4_uniform_01 ( int *seed );
float complex  c4_zero ( void );
float complex *c4mat_copy_new ( int m, int n, float complex a1[] );
float complex *c4mat_zero_new ( int m, int n );
float complex *c4vec_copy_new ( int n, float complex a1[] )
float complex *c4vec_unity ( int n );
float complex  cartesian_to_c4 ( float x, float y );
float complex  polar_to_c4 ( float r, float theta );
float          r4_uniform_01 ( int *seed );
void           sort_heap_external ( int n, int *indx, int *i, int *j, int isgn );
void          timestamp ( void );
