double *p00_data ( int prob, int dim_num, int data_num );
int p00_data_num ( int prob );
int p00_dim_num ( int prob );
int p00_prob_num ( void );
void p00_story ( int prob );
double *p01_data ( int dim_num, int data_num );
int p01_data_num ( void );
int p01_dim_num ( void );
void p01_story ( void );
double *p02_data ( int dim_num, int data_num );
int p02_data_num ( void );
int p02_dim_num ( void );
void p02_story ( void );
double *p03_data ( int dim_num, int data_num );
int p03_data_num ( void );
int p03_dim_num ( void );
void p03_story ( void );
double *p04_data ( int dim_num, int data_num );
int p04_data_num ( void );
int p04_dim_num ( void );
void p04_story ( void );
double *p05_data ( int dim_num, int data_num );
int p05_data_num ( void );
int p05_dim_num ( void );
void p05_story ( void );
double *p06_data ( int dim_num, int data_num );
int p06_data_num ( void );
int p06_dim_num ( void );
void p06_story ( void );
double *p07_data ( int dim_num, int data_num );
int p07_data_num ( void );
int p07_dim_num ( void );
void p07_story ( void );
double *p08_data ( int dim_num, int data_num );
int p08_data_num ( void );
int p08_dim_num ( void );
void p08_story ( void );
