void p00_ab ( int problem, int m, double a[], double b[] );
double *p00_f ( int problem, int m, int n, double x[] );
int p00_m ( int problem );
int p00_problem_num ( void );
double *p00_sol ( int problem, int m, int *know );
void p00_title ( int problem, char *title );
void p01_ab ( int m, double a[], double b[] );
double *p01_f ( int m, int n, double x[] );
int p01_m ( void );
double *p01_sol ( int m, int *know );
void p01_title ( char *title );
void p02_ab ( int m, double a[], double b[] );
double *p02_f ( int m, int n, double x[] );
int p02_m ( void );
double *p02_sol ( int m, int *know );
void p02_title ( char *title );
void p03_ab ( int m, double a[], double b[] );
double *p03_f ( int m, int n, double x[] );
int p03_m ( void );
double *p03_sol ( int m, int *know );
void p03_title ( char *title );
void p04_ab ( int m, double a[], double b[] );
double *p04_f ( int m, int n, double x[] );
int p04_m ( void );
double *p04_sol ( int m, int *know );
void p04_title ( char *title );
void p05_ab ( int m, double a[], double b[] );
double *p05_f ( int m, int n, double x[] );
int p05_m ( void );
double *p05_sol ( int m, int *know );
void p05_title ( char *title );
void p06_ab ( int m, double a[], double b[] );
double *p06_f ( int m, int n, double x[] );
int p06_m ( void );
double *p06_sol ( int m, int *know );
void p06_title ( char *title );
void p07_ab ( int m, double a[], double b[] );
double *p07_f ( int m, int n, double x[] );
int p07_m ( void );
double *p07_sol ( int m, int *know );
void p07_title ( char *title );
void p08_ab ( int m, double a[], double b[] );
double *p08_f ( int m, int n, double x[] );
int p08_m ( void );
double *p08_sol ( int m, int *know );
void p08_title ( char *title );
double *r8col_uniform_new ( int m, int n, double a[], double b[], int *seed );
double r8vec_max ( int n, double r8vec[] );
double r8vec_min ( int n, double r8vec[] );
void timestamp ( void );
