char ch_cap ( char ch );
int ch_eqi ( char ch1, char ch2 );
int ch_index_last ( char *s, char c );
int ch_is_digit ( char c );
char ch_low ( char ch );
int ch_to_digit ( char ch );
char ch_to_rot13 ( char ch );
char digit_inc ( char c );
char digit_to_ch ( int digit );
int file_column_count ( char *input_filename );
int file_exist ( char *filename );
char *file_name_ext_swap ( char *filename, char *ext );
void file_name_inc ( char *filename );
int file_row_count ( char *input_filename );
int i4_max ( int i1, int i2 );
int i4_min ( int i1, int i2 );
int i4_uniform ( int a, int b, int *seed );
int r4_nint ( float x );
double r8_uniform_01 ( int *seed );
int s_eqi ( char *s1, char *s2 );
int s_index_last_c ( char *s, char c );
int s_len_trim ( char *s );
void s_low ( char *s );
int s_to_i4 ( char *s, int *last, int *error );
int s_to_i4vec ( char *s, int n, int ivec[] );
double s_to_r8 ( char *s, int *lchar, int *error );
int s_to_r8vec ( char *s, int n, double rvec[] );
void s_to_rot13 ( char *s );
int s_word_count ( char *s );
void timestamp ( void );
